### ISSUE TITLE
Recruiter calls to the phone numbers

### ISSUE THREAD

**Issue by skade** [rubyberlin/code-of-conduct#131]
It seems like there's a number of recruiters using our page as a source for phone numbers.

We should either find some way of hiding those numbers (which I prefer not to) or clarify what the numbers are there for.

We should also devise a course of action. I'm perfectly fine with name-and-shame in this case.

**Comment by mroderick** [comment]
Recruiters that call me without invitation are added to my phone's block list as well as identified as spammers in https://www.truecaller.com.

After blocking the worst offenders (UK recruiters), I don't receive any cold calls from recruiters anymore.

Perhaps it could be stated on the page that any recruiters calling any of these numbers without invitation, will be added as spammers in https://www.truecaller.com?

In my opinion, that's not as harsh as naming and shaming.

**Comment by Xylakant** [comment]
I'm not affected in this instance, but blocking numbers is an individual fix and truecaller is a resource that not many people know about. I'd at least would like to have a list of numbers to block to make things easier for people to block spammers.

**Comment by bruderstein** [comment]
I don't think hiding numbers is a good idea for obvious reasons. Also, I think big scary warnings might not be the best idea as anybody who is in a troubled state may be put off reporting something that should not go unreported.

Perhaps something along the lines of "These contact details are provided for use in connection with the code of conduct only. Specifically, they should not be used for recruitment purposes."

**Comment by PragTob** [comment]
While I like the sentiment of adding a warning, I don't know if recruiters will read the page enough or care of they read it. I mean, I've had first hand stories of people being called about "family emergencies" that turned out to be recruiters.

We can do it, but I'm unsure about the impact. I also lack a better idea, sadly.

**Comment by skade** [comment]
After thinking about that for a while, we also don't have a good way to solve this. Feel free to react in any way you want to recruiters and make very clear this is unwelcome behavior. It's a bad behavior and should be called out, but agreeing with @PragTob. A statement would just lead to people not mentioning they got the number of the page or just completely ignoring it anyways.
