### ISSUE TITLE
“Jokes” Against Other Programming Languages

### ISSUE THREAD

**Issue by hagenburger** [rubyberlin/code-of-conduct#19]
@StephanSchmidt pointed out the often shown hate agains other programming languages within slides. Should we include that in our code of conduct?
https://twitter.com/codemonkeyism/status/491121132922486784

**Comment by lauralindal** [comment]
This is very specific (there are disses against coders/non-coders, other operating systems, etc) and I'd argue that programmers from (any) language are not part of a marginalized group. It derails from the larger power structures that this CoC wants to address. 

The concern about violent imagery / wording is already covered in another section of the CoC, too.
