### ISSUE TITLE
Bug: rendering cyrillic fails on some of the letters

### ISSUE THREAD

**Issue by nazarov-tech** [rubyberlin/code-of-conduct#190]
Thanks to @alextewpin for reporting it ([source](https://twitter.com/alextewpin/status/1052325667457650688))

Some letters in cyrillic are buggy :(

Example: the small letter `c` in the word `Кодекс`:

![bug](https://pbs.twimg.com/media/DpqcdCOWkAENPJ7.jpg)

And the whole text looking not quite.. good.

**Comment by teners** [comment]
@nazarov-tech this looks like two issues, actually. That small `c` must be Latin letter instead of Cyrillic one.

Overall it's a Typekit thing. All it takes is adding Russian to a project's Language Subsetting, and right now there are no Cyrillic glyphs, so it fallbacks to Times New Roman.
