### ISSUE TITLE
A note regarding a license for the BCoC?

### ISSUE THREAD

**Issue by catalanojuan** [rubyberlin/code-of-conduct#30]
I'm not sure if this is necessary or not but I've seen it in other CoCs like:

https://us.pycon.org/2012/codeofconduct/
https://amsterdam2014.drupal.org/code-of-conduct

Both of them use [Creative Commons Attribution 3.0](http://creativecommons.org/licenses/by/3.0/). I'm opening this issue as I couldn't find any discussion on this matter in the repo. 

I think it might be in favor of the use and distribution of it, but I'm no expert at all.

**Comment by 1000miles** [comment]
Addressed in PR #140 and merged. Closing.
