### ISSUE TITLE
Display of violence

### ISSUE THREAD

**Issue by PragTob** [rubyberlin/code-of-conduct#40]
We had an incident today, which still saddens me and I'm sorry about. :'(

The incident was about a display of brutal violence against animals. This was triggering to an attendee and others found it to be inappropriate as well.

I'm for adding this to the code of conduct, that such pictures are unwelcome. It can be tricky to formulate.

I'm happy to hear about ideas, input, whatever.

We have to figure out and implement #39 before we can move along with this.

Tobi

**Comment by eljojo** [comment]
Well this is a code of conduct, so I guess it's good to be "meta".
I'd like to raise two points:

- I wouldn't formulate strictly as pictures, because it could be text, sounds, whatever as well (for example). 

- Is it strictly "brutal violence against animals" that we dislike? what about "minor" violence? (in case there is such thing). Is it rather **cruelty** that we're against?

**Comment by Xylakant** [comment]
Is it strictly *cruelty* we're against? The CoC is referenced by multiple groups whose topic may or may not be as narrowly focused on technology as the rug_b. Banning the display or discussion of cruelty may ban beneficial discussions about those topics. I agree that rug_b is probably not the right place, but I consider this a slippery slope and I'd prefer to tread carefully.

**Comment by skade** [comment]
I agree with @xylakant that it's a difficult topic.

Still, some way to clarify that random and possibly triggering imagery/jokes not related to the topic of the group is worthwhile.

**Comment by Xylakant** [comment]
I'd include some generic verbiage that needless off-topic inclusion of triggering imagery is frowned upon, but leave it to the group to define what's on/off topic. I'd also include the desire that speakers warn about potentially triggering issues up front.

**Comment by skade** [comment]
eurucamp had foreign speakers contacting us before making Berlin wall references in Berlin. Encouraging speakers to contact the organizers if in doubt sounds like a good option.

**Comment by eljojo** [comment]
that sounds great! and it's also very flexible, because some communities might me more sensitive to certain topics than others.

**Comment by PragTob** [comment]
Thank you everyone for your input so far. Yes we should tread carefully.

Personally I will also make sure to always include information in emails to speakers, referencing the coc and giving a gist.

I like the idea of keeping it rather top level and flexible - some examples might be necessary, though. Many people don't know that a display of cruelty against animals can be triggering and hurtful to people in the audience.

**Comment by carpodaster** [comment]
+1 to what @Xylakant said about _needless_ and _off-topic_ inclusion. And if it "must" be included, can we suggest that the speaker issues a trigger warning in their presentation up front?

However, all of this assumes that the speaker is actually aware of the fact that his or her presentation may trigger people in their audience. 

(Disclaimer: I didn't attend rug b and don't know the actuall context)

**Comment by PragTob** [comment]
@carpodaster incident report coming up on the mailing list, as the topic comes up I'll see that I can do it rather sooner than later. Will link here.

**Comment by Xylakant** [comment]
There's no way to know what's triggering to your audience - there's just too many experiences people had and too many potential triggers. But there's also a pretty short list of things that are often triggering or at least warrant a warning. Maybe we could also add a short "speakers guidelines" amendment with - say - 10 questions that speakers could answer for themselves. This could raise awareness.

**Comment by myabc** [comment]
> I'd include some generic verbiage that needless off-topic inclusion of triggering imagery is frowned upon, but leave it to the group to define what's on/off topic.

:+1:

**Comment by svenfuchs** [comment]
> There's no way to know what's triggering to your audience - there's just too many experiences people had and too many potential triggers.

I think that's a derailing argument to make. It is safe to assume that for depictions of graphic violence chances are very high they'll be triggering, at least very hurtful. They shouldn't have a place at a user group or conference, and the CoC should make this clear, IMO.

**Comment by Xylakant** [comment]
@svenfuchs I beg to differ: If you read my comment in full, I'm exactly making the point that there's a short list that is highly triggering and we should explicitly mention this.

**Comment by thilo** [comment]
After some sleep I'm clearer now. I think we should leave it highlevel with the CoC because as pointed out before it is used by many groups with different cultural backgrounds. It is on us to fill this words with meaning by establishing practises and guidliness for the Berlin Ruby community. Adding some hint about triggering content with mentioned shortlist list of examples in speaker emails sounds like a good thing todo.

**Comment by Overbryd** [comment]
I would to add some critical thought material that might help reasoning about the direction we are heading:

* [George Charlin on Soft Language](https://www.youtube.com/watch?v=h67k9eEw9AY)
* [Steven Wittens "Storms and Teacups"](http://acko.net/blog/storms-and-teacups/#policy)

**Comment by xamebax** [comment]
> I think that's a derailing argument to make. It is safe to assume that for depictions of graphic violence chances are very high they'll be triggering, at least very hurtful. They shouldn't have a place at a user group or conference, and the CoC should make this clear, IMO.

Agreed. Animals or not, depictions of violence:
- without warning
- at a technical meetup

are completely unacceptable. There's a reason movies, movie trailers etc. are rated in the beginning: so you can consent to seeing them (or not).

@Overbryd, the pamphlet by Wittens you're quoting has unsettling gems like this: "You'll never see more talk of sexism and rape than on feminist websites." and in general shows quite poor logical reasoning and factual misinterpretations. Are you sure you want to lower the level of this discussion with such a poor piece of writing?

**Comment by Overbryd** [comment]
@xamebax Personally I don't think we should deepen this on a public platform, as I have given you enough attention after you reached out to me.

My contribution has its valid points, they might not all hit your nerve, I understand. I hope it opens up the discussion for more critical views.

**Comment by xamebax** [comment]
I do not understand why you're making this personal. I am a rug_b attendee taking part in a discussion on modifying its code of conduct. Don't see a reason for why you should get all patronizing about it.

**Comment by rentalcustard** [comment]
Hi everyone. A few observations from my point of view:

1. The effect the slide in question had on people yesterday was real and should not be trivialized or ignored, even if you don't understand it.
1. It's not absurd to think that we can find a non-exhaustive set of examples for triggering content. We should phrase the code of conduct on this point to recognize that the set is non-exhaustive, while expecting that an intelligent and diligent reader will be able to infer from the examples if their content might be of a similar kind.
1. We will all, at some point, fuck up, regardless of the wording of a code of conduct. While we should try to help each other not to fuck up as much as we can, our behaviour when we're told we've fucked up is really important too. I think we should recognize this in the code of conduct, and in our discussions around it.

<3

**Comment by Overbryd** [comment]
One paragraph out of Wittens "pamphlet" I like to consider is this:
> How many of the storms in teacups above would fall under this wide umbrella? If the yardstick to be applied is offense, then this basically forces everyone to walk on egg shells and admit guilt ahead of time.

I am happy with the different efforts to make the user group a safe place for everyone to enjoy. But when selecting and creating the contents for my talk, I don't want to consider every single potential sensitivity of the audience. I might step on somebodies toes in the future, unwillingly. But I am always willing to stand up for my mistakes and to talk about them.

That is why I think it would be good to keep it at the level on how we solved that yesterday. You told me that you didn't like the picture of my talk. I acknowledged what you said and was even willing to censor my upload on Speakerdeck for you to freely enjoy the actual content of the talk.

The thing with written rules or conducts: They might become very huge, and in the end are a minefield for the people creating content. You must acknowledge that there are different levels of sensitivity and different approaches to humour. And always, what the speakers think is okay to do, might not always be what the listeners thinks. That is an inherent problem of communication, and cannot be solved 100% ahead of time. **A sufficient solution for this problem in my point of view is to raise awareness between the conflicted individuals after something like this happens.**

**The written form of values of a user group should not become a "DO NOT" list of things.** I would opt for a conduct that encourages the core values and allows room for discussions.
Exactly as @rentalcustard put it: We might all at some point fuck up.
In my opinion that is okay, as long as we allow room to exchange the difference in opinions.

**Comment by rentalcustard** [comment]
Please don't quote selectively the part of my comment with which you agree, while disagreeing with the rest of it. :(

**Comment by Overbryd** [comment]
@rentalcustard  Just to make this clear: I disagree with 1 & 2 but I am agreeing with your 3rd opinion. I edited my comment above to emphasise that it doesn't look like I am stealing your agreement for my point.

**Comment by skade** [comment]
You are aware that that's basically accusing the person of lying for effect?

**Comment by Overbryd** [comment]
@skade no please educate me, what do you mean?

Sorry guys, this is my first time taking part in such a meta-discussion about rules and conducts. Honestly, you seem to have developed a very fine grained set of english that I definitely don't speak.

I am not a native english speaker, and I have no intend of accusing a person of lying for effect. So what is going wrong?

**Comment by xamebax** [comment]
@Overbryd, "I disagree with 1 & 2 but I am agreeing with your 3rd opinion."

@rentalcustard's point no 1 was
> 1. The effect the slide in question had on people yesterday was real and should not be trivialized or ignored, even if you don't understand it.

Lucas, you are continuing to be hurtful. You saw the state I was in yesterday and I assume you were listening to me when I told you my reaction was spending the rest of the talk in the bathroom, crying, shaking and hyperventilating to the point of nearly fainting. Now you are either accusing me of lying or trivalizing the state this situation put me in.

I feel extremely bad that after our conversation yesterday, when you seemed to understand what happened, you just decide to publicly state that my physically painful reaction to unconsented displays of gore was not real.

I am not the one who started getting into the details, so don't try pinning that to me.

**Comment by skade** [comment]
Statement one is:

> 1. The effect the slide in question had on people yesterday was real and should not be trivialized or ignored, even if you don't understand it.

You do disagree with the statement that the effect was real. There was at least one person that reacted emotionally to it, not just by "being offended".

**Comment by Overbryd** [comment]
Ups, that was not my intention. I was more concerned about the stealing the agreement thing than actually thinking exactly while editing. So rentalcustard wrote 'while disagreeing with the rest of it', and I thought I don't want to make it look like I am not differentiating his points so I quickly added my "whole" disagreement. That was meant for his opinion and not his observation.

I do not disagree with his observations, *I disagree with his opinion of creating a list of points that should be put up on the point of conduct.*
So I was a bit too quick and unthoughtful putting up my disagreement with 1 & 2, while 1 is an observation that I share with him and 2 is an opinion I do not.

Of course I saw the effect, and it was real, no disagreement of that. Sorry for the small uproar this caused here.

Wow, that escalated quickly.

**Comment by skade** [comment]
Okay, I'd like to reset this discussion to: https://github.com/rubyberlin/code-of-conduct/issues/40#issuecomment-73254060

@rentalcustard, @Overbryd, are you okay with that? (I asked all other persons)

**Comment by rentalcustard** [comment]
Fine.

**Comment by skade** [comment]
Okay, I'll start removing the posts as I have to leave my office to enjoy my evening. Should there be any disagreement, I've got a backup and can put them back up.

**Comment by skade** [comment]
There used to be a personal discussion here that we decided to remove. I have a backup. If anyone is interested, please don't hesitate to ping me on twitter (@argorak) or here and I might or might not give you information. We'd like to keep the discussion focused and these posts didn't add anything.

I'll also lock this issue for 24 hours and reopen it tomorrow. Please feel free to discuss the general Code of Conduct issue, but take extra care that we don't unnecessarily discuss personal feelings. Especially take care to not (even accidentally) question the validity of them.

**Comment by PragTob** [comment]
I'd like to continue this discussion.

I'd also like us all **not to make the discussion about people or the incident** but rather about the **proposed changes**, what these changes could look like and what the problems with the proposed changes are. If there are problems relating the incident, with people or other general off topic issues there are other channels to resolve this, a start would be to shoot me an email (tobi@rubyberlin.org).

I don't want anyone to walk on egg shells and feel like they have to watch their word at every step. At the same time I don't want members of our community to be hurt, feel disgusted or something like that (it's hard to formulate, sorry). We can't make a rule set that will cover everything anyone will ever find hurtful and we don't want to exclude perfectly good talk content.

I like the overall suggestion of @Xylakant to "include some generic verbiage that needless off-topic inclusion of triggering imagery is frowned upon" and include a short list that is highly triggering as well as the note that if in doubt or using one of those, it is appropriate to issue a trigger warning. (please tell me if I forgot something important)
I like this suggestion because it stays high level, includes concrete examples and at the same time makes this coc still viable for groups and presentations that might depend on that imagery as it could be the talk topic. It also encourages speaker to think more about the content they are exposing the audience to.

I'll also make sure to communicate this clearly to the speakers, including a link and the offer that they can contact me/the team at any time if they have questions/are looking for feedback.

This should raise awareness beforehand and therefore help to avoid incidents and bolster an inclusive and welcoming community. And I believe that as a group, this should be one of our goals.

Please discuss :)

**Comment by svenfuchs** [comment]
> I don't want anyone to walk on egg shells and feel like they have to watch their word at every step.

I am wondering what's wrong with walking on egg shells. Is watching our words as carefully as we can not exactly what we want to learn, encourage, and do?

In my opinion we cannot possibly be over-cautious, and it is good for us to put clear restrictions in place. If that raises additional discussion amongst people who aren't aware of issues, then that's good. If it drives someone away who doesn't want to open up to any discussion, but makes the event a safer place for others to join overall, then that's fine, too.

You've been brave enough to take a clear stand in the past. Please continue :)

> "include some generic verbiage that needless off-topic inclusion of triggering imagery is frowned upon" and include a short list that is highly triggering as well as the note that if in doubt or using one of those, it is appropriate to issue a trigger warning.

I think a non-exhaustive list of examples of unwanted behaviour is an integral part of a good CoC. 

"Frowned upon" sounds softening to me. We want this to not be happening, right? So why not just say it's unacceptable.

Also, the trigger warning doesn't make sense to me in the context of technical talks at user groups, conferences, and such, except there's a meta talk e.g. addressing issues within our community which might refer to triggering topics. These probably should *require* trigger warnings, but also never include any disturbing imagery of any kind.

As for the problem that this CoC needs to be generic enough for others to use as well, I'd like to question that. I tend to think the CoC used by RugB and eurucamp should reflect whatever we know about a good CoC at any point, and this should take priority. If this conflicts with requirements for other organizations or events then there should be a mechanism to add event specific content, or just fork it. 

All that said, since I'm not an active organizer in any of these events, I'm just dropping by to voice my opinion as a bystander, and occasional visitor.

**Comment by Xylakant** [comment]
> As for the problem that this CoC needs to be generic enough for others to use as well, I'd like to question that.

This is the CoC Ruby Berlin e.V. enforces on all activities, venues, conferences that it supports in any way. That's the issue with being extremely strict - we limit our reach. I totally support that RugB and eurucamp use a stricter version, but I don't think that should be the case for the Ruby Berlin one.

**Comment by PragTob** [comment]
@svenfuchs your feedback is highly appreciated and super welcome, please continue :+1: :) I don't have much time right now but definitely thanks a lot for your input - some of the terms I used weren't to the point of what I meant - for instance frowned upon, it should definitely not be softening like this word. We need better words - I'd try to get the basic direction down here and formulate it correctly in the PR. More reply incoming :)

In general, we welcome the input of everyone.

**Comment by rentalcustard** [comment]
> That's the issue with being extremely strict - we limit our reach.

I don't understand this comment. Does it mean that some behaviours are acceptable at some rubyberlin events and not at others?

**Comment by Xylakant** [comment]
@rentalcustard That's what I'm saying. Some events may limit their scope to "we're strictly technical and don't do meta discussions that may involve triggering topics" while other events may explicitly want to include such talks - and we as Ruby Berlin e.V. should be in a position to support them. As an example, think about a hypothetical conference about ruby in gaming and one of the proposed talks wants to pick up the gamergate discussion and the threats against the women involved. Such a talk could rightfully include triggering descriptions or imagery. If our CoC contains a blanket ban against triggering imagery and descriptions we'd be in what I perceive as a bad position:

* either we don't support such a conference
* or we force the organizers to abandon the talk
* or we make an exception and do not enforce our CoC at all
* or we draft a special CoC that we require for that conference

I like neither of those options. I'd prefer that we as Ruby Berlin have CoC that takes into account that there's a range of events, from purely technical to purely meta that have different topics and thus may need a different CoC. But I also want us to enforce a common baseline, for example the strict requirement for trigger warnings if such topics are brought up in a talk.

On a more philosophical note I'm opposed to exhaustive lists of "forbidden" things. IMHO this leads to people doing stupid list checking - my stuff not on the list, so I'm fine. But that's not what we want - we want speakers and attendees to think about what they're saying and to check their own behavior towards others. I think that goal is better reached by enforcing a baseline and ask speakers to check in with the organizers when in doubt.

**Comment by skade** [comment]
I'd like to note that the FOSDEM Bird of the feathers about CoCs had a very interesting discussion about the "list of things" problem with no final conclusion.

I guess it boils down to this: is the Berlin Code of Conduct intended for our UGs first on only incidentally for others or does it aim to be easily applicable for many?

**Comment by svenfuchs** [comment]
It seems to me that the current CoC already contains a non-exhaustive list of example when it comes to the definition of harassment. And it mentions:

> inappropriate use of nudity and/or sexual images in public spaces (including presentation slides)

Why not add "Content that is known to be highly triggering such as imagery or depictions of violence is also unacceptable."

With regards to the problem of this CoC being meant to be used for other events, are there any examples of actual events (past or planned) that would actually welcome such content? Is this something that could be taken care of as soon as Ruby Berlin e.V. actually plans to support such an event?

**Comment by Xylakant** [comment]
> Why not add "Content that is known to be highly triggering such as imagery or depictions of violence is also unacceptable."

-1 from my side, as discussed above. There are valid reasons to include triggering content in talks. The current wording has the "inappropriate" qualifier, which allows for such content as long as it's appropriate for the talk. 

> With regards to the problem of this CoC being meant to be used for other events, are there any examples of actual events (past or planned) that would actually welcome such content? Is this something that could be taken care of as soon as Ruby Berlin e.V. actually plans to support such an event?

We usually decide to support events before the exact list of speakers and talks are known. I don't see how this could work in practice - an extraordinary meeting of the ruby berlin e.V. members if an interesting talk gets submitted? The Vorstand gets to make exemptions at his discretion? One member of the Vorstand, qualified majority?

**Comment by PragTob** [comment]
As this has also become sort of an issue of the general applicability of the coc, events organized by rubyberlin et. al. and we have a meeting tomorrow I proposed to talk about this there tomorrow. Dunno if it's too late to put it on the agenda but I guess I'll know tomorrow.

**Comment by bitboxer** [comment]
@PragTob did you talk about this on the Verein? I think we should meet in person and talk about all this. Reading this long long discussion lets me think that a personal meeting to discuss this might help. This is a very hard topic and discussing it on a platform that removes the social clues is maybe too problematic.

What do you all think?

**Comment by rentalcustard** [comment]
I think the longer we talk about it, the more complicated we make it seem.

From my perspective it seems simple. We had an incident which made an attendee feel uncomfortable in our space, and we want our CoC to make it clear that this isn't something we want to happen in future.

It seems like the only outstanding question was about the applicability of the CoC, and *that* was to be discussed offline. What was the outcome of that discussion, and when can we get this change to the CoC which applies to rug-b?

**Comment by rentalcustard** [comment]
Apologies, it seems like there was also an open question about the wording. I think we should use this thread to agree to make a change and where it should be made. Then make a PR to some repo where we discuss the specific wording.

**Comment by rentalcustard** [comment]
Also: general reminder that 'meet in person' sounds a lot different to those affected by an incident than to those without an interest in it. Let's try and keep our vulnerable members in mind.

**Comment by eljojo** [comment]
If someone's interested in opening a PR, **this** is that it should be opened against. The files are here: https://github.com/rubyberlin/code-of-conduct/tree/master/source/localizable

Also, it might be worth referencing to this issue (#40) when opening the PR.

**Comment by rentalcustard** [comment]
@eljojo @PragTob @skade @myabc sorry for the catch-all message, but I'm not sure who are the maintainers of this repository, so I looked at recent committers. It'd be good to get some comment here and/or on #45, especially considering rug-b is taking place on Thursday.

What happened in the meeting regarding applicability of the CoC?

Are we happy with the amendment proposed in #45? How do we get it applied?

**Comment by skade** [comment]
No problem. I'd just like to add the stance of the Verein from the last meeting. The general consensus was that the change should be done carefully, across all versions of the CoC and that the maintainers of the CoC are trusted in that regard.

**Comment by xamebax** [comment]
> The general consensus was that the change should be done carefully, across all versions of the CoC and that the maintainers of the CoC are trusted in that regard.

I'm sorry, I don't fully understand this sentence. Could you elaborate?

**Comment by skade** [comment]
@xamebax There's not much to elaborate :). Careful in a sense that we don't want to end up editing it 5 times, making it harder for translators. Trusted no one of the Verein saw specific need to bring that up as an internal vote again.

**Comment by xamebax** [comment]
Great. Could anyone address this, then?

> Are we happy with the amendment proposed in #45? How do we get it applied?

**Comment by PragTob** [comment]
Hi everyone,

I'm sorry I'm a bit overworked with me moving this weekend + lots of other responsibilities (and getting sick inbetween) so I haven't tended to this as I should, I'm sorry but right now I can't really make enough time for this. 

I'd put myself, @hagenburger @thilo and @skade as maintainers of this repo. Individuals may disagree :P 

Before getting this change #39 needs to be sorted out which is no small task. We won't make it in time for tomorrow's rug_b. I hope we can make it for next rug_b. Help appreciated.

Here are the notes from the vereins meeting, with names removed, it's German and I don't have time to translate it right now, sorry. Also the notes aren't very good on this topic (I was the note taker, and as you can imagine I was hugely engaged in the discussion it's not easy to take notes then).

> Code of conduct Diskussion: Vorstellung des Problems des Ausschlusses von Darstellung von Gewalt und andere Problemen. Wie wird es generell gehandhabt, was für Vortrage haben wir. Expected behavior ist sehr breit.
>
> Jemand wirft ein dass die konkreten Beispiele als Inklusion in den CoC schwierig sind, da er eher offen ist (expected behavior vs. unacceptable behavior). Vorschlag, ein Extradokument mit Beispielen etc.
> Man sollte als Ausrichter auf diese Dinge aufmerksam machen. 
> Beispiele evtl. in einer FAQ/Anhang/Paragraph ( → konkrete Beispiele evtl. aus eurucamp/jrubyconf/rugb)
> Doch ein Beispiel rein wie Gewaltdarstellung oder ähnliches in den CoC? Oder etwas allgemeineres? Beigegeben als Erfahrungsschatz.
> → Unterschied unacceptable behavior (raus, eine Diskussion), expected behavior → eventuelle Grauzone
> Thema vertagt wegen begrenzter Zeit, kleiner Gruppe wird vertagt

Cheers,
Tobi

**Comment by PragTob** [comment]
Also noteworthy #43 - we now even have schools/organizations signing the coc so the question about it being open to more events becomes even more relevant.

Tobi

**Comment by rentalcustard** [comment]
Thanks for the update Tobi. How can interested individuals help with #39?

I still don't understand the issue with wider applicability. I can't imagine wanting to be affiliated with events where inappropriate depictions of violence are OK.

**Comment by skade** [comment]
@rentalcustard I guess the point was more that there are moments in which triggering media are okay, e.g. in the context of discussing it. I would be hard pressed to find an example on a direct IT topic.

I'm not sure on where do go with that discussion though, as this is at the organisers discretion anyways. Possibly, just saying that exceptions can be made under organiser review based on the topic of the talk would suffice.

**Comment by PragTob** [comment]
Ah damn I didn't answer here... sorry :-/

About help with #39 - what can be done is discussing the ideas presented there, like a change process. Also to implement a mechanism for versioning (e.g. orgs may support different versions of the coc). I'll comment again there. @rentalcustard

**Comment by PragTob** [comment]
I posted a suggested amendment in #54

**Comment by skade** [comment]
Closed by 45.
