### ISSUE TITLE
Gendering in der deutschen Version

### ISSUE THREAD

**Issue by skade** [rubyberlin/code-of-conduct#44]
Ich schreib das mal auf deutsch, betrifft ja sonst niemanden :).

Es ist die Frage aufgekommen, warum der deutsche Text nicht gegendert ist, also darauf geachtet wurde, keine Worte zu verwenden, die standardmässig einem Geschlecht zugeordnet sind - zum Beispiel "Teilnehmer" (generisches Maskulinum).

Wenn wir das machen wollen, müssen wir uns auch überlegen, wie.

Ich persönlich bin im allgemeinen Freund von [Neutralisierung](http://de.wikipedia.org/wiki/Geschlechtergerechte_Sprache#Neutralisierung) - da stört sich am Ende niemand dran und ich finds eigentlich auch selten holprig. Zum Beispiel ließe sich "Teilnehmer" durch "Teilnehmende" ersetzen. Das stößt selten jemandem auf und ich bin da gerne diplomatisch.

Alternative ist natürlich auch die [Sichtbarmachung](http://de.wikipedia.org/wiki/Geschlechtergerechte_Sprache#Sichtbarmachung) - zu den Beispielen dazu gibt es natürlich noch die Formen mit `*` und `_`. Ich hab da auch kein grundsätzliches Problem mit und kann das gut vertreten, kann mir aber mehr Diskussionen an der Stelle vorstellen.

**Comment by PragTob** [comment]
Danke fuer das issue Flo.

Ich waere auch fuer die Neutralisierung. :)

**Comment by Morred** [comment]
Bin auch eher ein Freund der Neutralisierung :)

**Comment by chastell** [comment]
+½ für die Neutralisierung. Das ist was wir in der polnischen Übersetzung verwendet und es ist leichter zu lesen. (Pardon my German!)

**Comment by hagenburger** [comment]
+1 für Neutralisierung und Lesbarkeit :)

**Comment by humpaaa** [comment]
+1 Neutralisierung

**Comment by PragTob** [comment]
Wir sind also fuer die Neutralisierung, wenn jemand das uebernehmen koennte waere ich dankbar :) Ich habs gerade mal probiert und bin da nicht so gut vorangekommen - hoffentlich kann es wer anders besser :)

bspw. was macht man aus `Zeuge`?

**Comment by Morred** [comment]
Dem Geschehen beiwohnende Personen? xD

**Comment by humpaaa** [comment]
In der englischen Variante wird 'witness' ja als Verb und nicht als Substantiv verwendet.

> If You Witness or Are Subject to Unacceptable Behavior

und 

> If you are subject to or witness unacceptable behavior

Wenn man also *to witness* mit *etwas miterleben* und nicht mit *Zeuge* übersetzt, hat man kein Geschlechts-Problem.

Bei der Gelegenheit fällt mir auf, dass *Subject* mit *Opfer* übersetzt wurde. Der Begriff *Opfer* wird aber gemeinhin abgelehnt

> Da die Bezeichnung „Opfer“ mit Ohnmacht, Hilflosigkeit, Schwäche, etc. gleichgesetzt wird, birgt sie für Betroffene auch die Gefahr, auf diese Attribute dauerhaft festgelegt zu werden. 
[Quelle](http://netzwerkb.org/2011/01/13/was-kritisieren-wir-am-begriff-opfer-bzw-am-umgang-damit/)

Hier wäre es sinnvoller, von Betroffenen bzw. *betroffen von* zu sprechen (was dem im Englischen verwendeten Begriff *Subject* auch eher entspricht)

**Comment by PragTob** [comment]
Danke @humpaaa da kann man was draus machen. Wir sind hier sehr gerne offen fuer pull requests, um das zu beheben!

**Comment by skade** [comment]
Das wurde durch PR #53 bereits gelöst, zusammen mit den Vorschlägen von @humpaaa .
