### ISSUE TITLE
Anyone wants to get codeofconduct.berlin? :)

### ISSUE THREAD

**Issue by finnp** [rubyberlin/code-of-conduct#56]
Would be cool if the CoC would be accessible through a domain like this. :sunflower: 

PS: By anyone I kinda mean Ruby Berlin e.V.

**Comment by myabc** [comment]
codeofconduct.ruby.berlin and we'd save a few €'s

**Comment by hagenburger** [comment]
We already bought a domain a little while ago :)

@thilo do you think you could set it up for tonight’s RUG-B?

**Comment by thilo** [comment]
registered http://berlincodeofconduct.org/ some time ago. And now set it up. Sorry after failed initial attempt I forgot about it.

**Comment by hagenburger** [comment]
Now it’s all set up :)

http://berlincodeofconduct.org

**Comment by finnp** [comment]
Awesome :heart:
