### ISSUE TITLE
What is the license for this work?

### ISSUE THREAD

**Issue by osg** [rubyberlin/code-of-conduct#57]
I need to emulate this doc and need to know how to adhere to the license.

**Comment by hagenburger** [comment]
Thank you for opening this issue, we do need to add this.

The [Pdx.rb CoC](http://pdxruby.org/codeofconduct) has a “Creative‭ ‬Commons‭ ‬Attribution-ShareAlike” license so this should also apply to our CoC. I’m not sure about the version they refer to.

**Comment by skade** [comment]
Creative Commons Attribution-ShareAlike. It's not apparent from the page, #52 is going to fix that.

Happy to see your interest.

**Comment by opensourcegrrrl** [comment]
@skade Thanks for the reply. To be clear, I think you are referring to the international version that can also be used for commercial purposes. See http://creativecommons.org/licenses/by-sa/4.0/. Please correct me if I am wrong.

**Comment by skade** [comment]
This is fixed. @osg you are right there, https://creativecommons.org/licenses/by-sa/4.0/ is meant.
