### ISSUE TITLE
Adding license to this so others can derive their CoC from this

### ISSUE THREAD

**Issue by thilo** [rubyberlin/code-of-conduct#68]
Hi just got the request to build on our Code of Conduct. Do we allow derived work? And can we add this to the repo? does MIT apply for example of Creative Commons?

**Comment by hagenburger** [comment]
One idea of the Berlin Code of Conduct was to provide a CoC that is:
* well-known
* everybody knows the content
* avoiding fragmentation in details
* collect all community voices to improve

So this might be slightly against this idea but as it’s Creative Commons I don’t see any problem if somebody wants to build an own version. Did they provide any more details?

**Comment by PragTob** [comment]
Well we are Creative Commons like the pdx.rb we derived from :) It should be more public though what direct license we use, though. I think it's creative commons share alike.

**Comment by chastell** [comment]
Well https://github.com/rubyberlin/code-of-conduct/pull/52 is still open and waits for the _green_ button to be pushed. ;)

**Comment by PragTob** [comment]
err. No it isn't.

**Comment by PragTob** [comment]
That was a joke of course, thanks @chastell for reminding my lazy ass. All merged. All good.

**Comment by chastell** [comment]
YOU AND YOUR JOKES. Good thing you’ll be able to explain yourself in person NEXT WEEK, WOO! :fireworks: :sparkling_heart:

**Comment by PragTob** [comment]
:heart: :dancers: :dancers: :dancer: :dancers: :dancers: :heart:
