### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by hagenburger** [rubyberlin/code-of-conduct#7]
As soon as it is live it should be tagged as v1.0.0 and included in the live version.

**Comment by PragTob** [comment]
Bump.

**Hugely important** when we want to amend this code of conduct and add new rules as we can't just change it as quite some user groups are referring to it.

**Comment by finnp** [comment]
I suggest keeping around a version number in the data folder (maybe meta.json) and then use a semver-like versioning:

* major: significant "breaking" changes
* minor: additions to the code of conduct
* patch: correct spelling, formatting 

After a PR gets merged, someone changes the version number as well. Organizers get informed at least about minor and major changes, probably not about "patches".

**Comment by eljojo** [comment]
I like @finnp's idea a lot!

**Comment by hagenburger** [comment]
“Additions” is not like adding a feature in software without breaking it. It might make it stricter which you might compare to removing a feature (breaking). I would go for:

* major: significant “breaking” changes and additions to the code of conduct
* minor: updating/changing/clarifying existing parts without changing their intension
* patch: correct spelling, grammar, formatting

-----

Also a list of changes which should not change the version number:

* Design
* Browser fixes
* Adding/removing of supporters
* Updates in the contacts list of supporters
* Adding a new language (new languages should always adopt the latest version)

-----

For the process: We can’t just update the version number after pull requests. As long as it’s more than a patch, all languages have to be updated first.

**Comment by finnp** [comment]
Right now PRs are against master and then deployed to gh-pages right? So the versioning could be done before publishing to gh-pages.

**Comment by 1000miles** [comment]
**Update, Sun, 2017-09-10**

Today @yuiofthesun, @skade and me decided to use tagging for the releases (as previously proposed by @hagenburger ) and link them from the website. Closing.
